# Generated by Django 3.1.3 on 2020-12-22 07:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_friend'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='friend',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='friend',
            name='lives_in',
        ),
        migrations.RemoveField(
            model_name='friend',
            name='nick_name',
        ),
    ]
